import type { Metadata } from "next";
import { aiInsights } from "@/lib/climate-data";
import AIInsightCard from "@/components/AIInsightCard";

export const metadata: Metadata = {
  title: "AI Insights | WildTerminator Climate Vision",
  description: "AI-powered climate insights and environmental intelligence generated by our advanced machine learning models.",
};

export default function AIInsightsPage() {
  const criticalCount = aiInsights.filter((i) => i.severity === "critical").length;
  const warningCount = aiInsights.filter((i) => i.severity === "warning").length;
  const avgConfidence = Math.round(
    aiInsights.reduce((sum, i) => sum + i.confidence, 0) / aiInsights.length
  );

  return (
    <div className="pt-20 pb-16">
      {/* Header */}
      <section className="py-12 relative">
        <div className="absolute inset-0 bg-gradient-to-b from-emerald-950/20 to-transparent" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center space-x-2 mb-4">
            <span className="w-2 h-2 bg-emerald-400 rounded-full animate-pulse" />
            <span className="text-emerald-400 text-sm font-medium">AI-Powered Analysis</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Climate AI Insights
          </h1>
          <p className="text-gray-400 text-lg max-w-3xl">
            Real-time environmental intelligence generated by our advanced machine
            learning models. Each insight is validated against peer-reviewed data
            sources with confidence scoring.
          </p>
        </div>
      </section>

      {/* Stats Bar */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-10">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="bg-gray-900/60 border border-gray-800 rounded-xl p-4 text-center">
            <div className="text-2xl font-bold text-white">{aiInsights.length}</div>
            <div className="text-gray-400 text-sm">Active Insights</div>
          </div>
          <div className="bg-red-950/30 border border-red-800/30 rounded-xl p-4 text-center">
            <div className="text-2xl font-bold text-red-400">{criticalCount}</div>
            <div className="text-gray-400 text-sm">Critical Alerts</div>
          </div>
          <div className="bg-amber-950/30 border border-amber-800/30 rounded-xl p-4 text-center">
            <div className="text-2xl font-bold text-amber-400">{warningCount}</div>
            <div className="text-gray-400 text-sm">Warnings</div>
          </div>
          <div className="bg-emerald-950/30 border border-emerald-800/30 rounded-xl p-4 text-center">
            <div className="text-2xl font-bold text-emerald-400">{avgConfidence}%</div>
            <div className="text-gray-400 text-sm">Avg Confidence</div>
          </div>
        </div>
      </section>

      {/* Insights */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {aiInsights.map((insight, index) => (
            <AIInsightCard key={insight.id} insight={insight} index={index} />
          ))}
        </div>
      </section>

      {/* AI Models Info */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-16">
        <div className="bg-gradient-to-br from-gray-900/60 to-gray-900/40 border border-gray-800 rounded-2xl p-8">
          <h2 className="text-2xl font-bold text-white mb-4">About Our AI Models</h2>
          <p className="text-gray-400 text-base leading-relaxed mb-6">
            WildTerminator&apos;s AI Climate Lab operates seven specialized machine learning
            modules that continuously process environmental data from satellite imagery,
            atmospheric sensors, ocean monitoring systems, and ground-based observations.
            Our models are trained on peer-reviewed datasets and validated against
            established climate science benchmarks.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {[
              {
                name: "Climate Data Modeler",
                desc: "Global temperature and atmospheric pattern analysis",
                accuracy: "94.7%",
              },
              {
                name: "Carbon Tracker",
                desc: "CO₂ and greenhouse gas emission trend analysis",
                accuracy: "92.1%",
              },
              {
                name: "Biodiversity Monitor",
                desc: "Species vulnerability and habitat risk scoring",
                accuracy: "89.3%",
              },
              {
                name: "Forest Sentinel",
                desc: "Deforestation detection and prediction",
                accuracy: "96.2%",
              },
              {
                name: "Hazard Forecaster",
                desc: "Extreme weather event prediction and alerting",
                accuracy: "91.3%",
              },
              {
                name: "Ecosystem Analyzer",
                desc: "Restoration impact and sustainability modeling",
                accuracy: "88.7%",
              },
            ].map((model, i) => (
              <div
                key={i}
                className="bg-gray-800/30 border border-gray-700/50 rounded-xl p-4"
              >
                <h3 className="text-white font-semibold text-sm mb-1">{model.name}</h3>
                <p className="text-gray-400 text-xs mb-2">{model.desc}</p>
                <div className="flex items-center space-x-2">
                  <div className="flex-1 bg-gray-700 rounded-full h-1.5 overflow-hidden">
                    <div
                      className="h-full bg-emerald-500 rounded-full"
                      style={{ width: model.accuracy }}
                    />
                  </div>
                  <span className="text-emerald-400 text-xs font-medium">{model.accuracy}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
